Repository LiskHQ/lisk-scripts, pull requests merged in 2018-08, with the labels that each got.

#122 Correct typo - Closes #117
  packaged/lisk_snapshot.sh
Labels: :eye: pending review

#127 Add some sanity checks to lisk_bridge.sh - Closes #126
  downloaded/lisk_bridge.sh
Labels: enhancement

#128 Add some sanity checks to lisk_bridge.sh
  downloaded/lisk_bridge.sh
Labels: enhancement

#134 Fix jq path
  downloaded/installLisk.sh
Labels: bug
