Repository LiskHQ/lisk-scripts, pull requests merged in 2018-05, with the labels that each got.

#47 Fix snapshotting for 1.0
  packaged/lisk_snapshot.sh
Labels: :eye: pending review, bug

#49 Run ShellCheck on Jenkins (Issue #20) for 0.2.0 branch
  Jenkinsfile
  downloaded/installLisk.sh
  packaged/lisk.sh
  packaged/lisk_bridge.sh
Labels: easy, jenkins

#55 Remove sudo from installLisk.sh - Closes #54
  downloaded/installLisk.sh
Labels: :eye: pending review, security

#58 Remove config migration lisk bridge - Closes #51
  packaged/lisk_bridge.sh
Labels: :eye: pending review

#57 Add non-interactive mode to installLisk.sh
  downloaded/installLisk.sh
Labels: :eye: pending review, enhancement

#65 Cleanup lisk_bridge.sh
  downloaded/lisk_bridge.sh
  packaged/lisk_bridge.sh
Labels: :eye: pending review

#72 Fix local tar argument passing in lisk_bridge.sh
  downloaded/lisk_bridge.sh
Labels: :eye: pending review, bug

#75 Delete packaged/etc/snapshot.json
  packaged/etc/snapshot.json
Labels: :eye: pending review

#76 Fix snapshot - Closes #73
  packaged/lisk_snapshot.sh
Labels: :eye: pending review

#78 Use jq instead of grep - Closes #77
  packaged/lisk.sh
  packaged/lisk_snapshot.sh
  packaged/tune.sh
Labels: :eye: pending review

#79 Ensure jq uses raw output
  packaged/lisk_snapshot.sh
Labels: :eye: pending review
